import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Gradenet IT topic",
  description: "Generated by DreamerWebdev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <main className="h-screen w-full md:max-w-7xl mx-auto">
          <Navbar/>
        {children}
        </main>
      </body>
    </html>
  );
}
